# Generated by Django 3.1.7 on 2021-03-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domicilio', '0001_initial'),
        ('personas', '0001_initial'),
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domicilio.direccion')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers2', to='personas.persona')),
                ('telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono2', to='contactos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='TutorA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domicilio.direccion')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers1', to='personas.persona')),
                ('telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono1', to='contactos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domicilio.direccion')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers3', to='personas.persona')),
                ('telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono3', to='contactos.contacto')),
                ('tutor_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a', to='alumnos.tutora')),
                ('tutor_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b', to='alumnos.tutorb')),
            ],
        ),
    ]
