# Generated by Django 3.1.7 on 2021-03-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depto', '0001_initial'),
        ('personas', '0001_initial'),
        ('domicilio', '0001_initial'),
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depto.depto')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion', to='domicilio.direccion')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers', to='personas.persona')),
                ('telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefono', to='contactos.contacto')),
            ],
        ),
    ]
